CRUDoperation/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('book_list.urls')),
]

book_list/urls.py
from django.urls import path, include
from .views import HomeView, BookAddView, BookUpdateView, BookDeleteView, BookSearchView

app_name = 'book_list'
urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('book/add/', BookAddView.as_view(), name='book-add'),
    path('book/<int:pk>/update/', BookUpdateView.as_view(), name='book-update'),
    path('book/<int:pk>/delete/', BookDeleteView.as_view(), name='book-delete'),
    path('book/search/', BookSearchView.as_view(), name='book-search'),
]

book_list/models.py
from django.db import models


class Category(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class BookList(models.Model):
    name = models.CharField(max_length=200)
    author = models.CharField(max_length=200)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    publication = models.CharField(max_length=200, null=True, blank=True)

    class Meta:
        ordering = ['name']

book_list/forms.py
from django import forms
from .models import BookList


class BookForm(forms.ModelForm):
    class Meta:
        model = BookList
        fields = '__all__'
        labels = {'name': 'Book Name'}
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control mt-1', 'placeholder': 'Enter Book Name'}),
            'author': forms.TextInput(attrs={'class': 'form-control mt-1', 'placeholder': 'Enter Author Name'}),
            'publication': forms.TextInput(
                attrs={'class': 'form-control mt-1', 'placeholder': 'Publisher of the book'}),
            'category': forms.Select(attrs={'class': 'form-control mt-1'})
        }

    def __init__(self, *args, **kwargs):
        super(BookForm, self).__init__(*args, **kwargs)
        self.fields['category'].empty_label = "Select Book Category"

book_list/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.views import View
from .models import BookList
from .forms import BookForm
from django.db.models import Q


class HomeView(View):
    def get(self, request):
        books = BookList.objects.all()
        context = {'books': books}
        return render(request, 'book_list/home.html', context)


class BookAddView(View):
    def get(self, request):
        form = BookForm(label_suffix='')
        context = {'form': form}
        return render(request, 'book_list/book_form.html', context)

    def post(self, request):
        form = BookForm(request.POST, label_suffix='')
        if form.is_valid():
            form.save()
            messages.success(request, f'Book Data Added To The list')
            return redirect('book_list:home')


class BookUpdateView(View):
    def get(self, request, pk):
        book = BookList.objects.get(pk=pk)
        form = BookForm(instance=book, label_suffix='')
        context = {'form': form}
        return render(request, 'book_list/book_form.html', context)

    def post(self, request, pk):
        book = BookList.objects.get(pk=pk)
        form = BookForm(request.POST, instance=book, label_suffix='')
        if form.is_valid():
            form.save()
            messages.success(request, f'Book Data Updated')
            return redirect('book_list:home')


class BookDeleteView(View):
    def get(self, request, pk):
        book = BookList.objects.get(pk=pk)
        context = {'book': book}
        return render(request, 'book_list/book_delete.html', context)

    def post(self, request, pk):
        book = BookList.objects.get(pk=pk)
        book.delete()
        messages.success(request, f'Book Deleted')
        return redirect('book_list:home')


class BookSearchView(View):
    def get(self, request):
        query = request.GET.get('q').strip()
        if query:
            books = BookList.objects.filter(Q(name__icontains=query) | Q(author__icontains=query) |
                                            Q(category__name__icontains=query) | Q(publication__icontains=query))
        else:
            books = BookList.objects.none()
        context = {'books': books, 'query': query}
        return render(request, 'book_list/book_search.html', context)

book_list/templates/book_list/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
    <link rel="stylesheet" href="{% static 'book_list/css/style.css' %}">

    <title> {% block title %} {% endblock title %} </title>

    <style>{% block css %} {% endblock css %}</style>
</head>

<body>
<div class="container p-4 my-4 shadow bg-light">
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
                {{ message }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        {% endfor %}
    {% endif %}
    <div class="section">
        <fieldset class="form-group p-4">
            <h2 class="text-center text-success mb-4">Book Corner - Collection of Books</h2>
            <hr>
        </fieldset>
    </div>

    {% block body %} {% endblock body %}
</div>

<footer class="bg-dark text-light position-fixed fixed-bottom">
    <p class="text-center py-2 my-0">Copyright &copy; 2021 | All rights reserved</p>
</footer>

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.6.0.js"
        integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk="
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"
        integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js"
        integrity="sha384-Atwg2Pkwv9vp0ygtn1JAojH0nYbwNJLPhwyoVbhoPwBhjQPR5VtM2+xf0Uwh9KtT"
        crossorigin="anonymous"></script>

{% block js %} {% endblock js %}
</body>
</html>

book_list/templates/book_list/book_delete.html
{% extends 'book_list/base.html' %}

{% block title %} Book Corner - Delete Book {% endblock title %}

{% block css %} {% endblock css %}

{% block body %}
<div class="col-md-8 border shadow-sm offset-md-2 p-4 my-4">
    <form method="post" class="p-4"> {% csrf_token %}
        <fieldset>
            <h2 class="mb-4">Are you sure you want to delete the book "{{ book.name }}"?</h2>
        </fieldset>
        <div class="form-group mt-4">
            <button type="submit" class="btn btn-danger me-2">Yes, Delete</button>
            <a href="{% url 'book_list:home' %}" class="btn btn-secondary">Cancel</a>
        </div>
    </form>
</div>
{% endblock body %}

{% block js %} {% endblock js %}

book_list/templates/book_list/book_form.html
{% extends 'book_list/base.html' %}

{% block title %} Book Corner {% endblock title %}

{% block css %} {% endblock css %}

{% block body %}
<div class="col-md-8 border shadow-sm offset-md-2 p-4 my-4">
    <form method="post" class="p-4">  {% csrf_token %}
        {% for item in form %}
            <div class="mb-3">
                {{ item.label_tag }} {{ item }}
                <small class="text-danger">{{ item.errors|striptags }}</small>
            </div>
        {% endfor %}
        <div class="form-group mb-3">
            <button type="submit" class="btn btn-outline-primary mt-4 me-2">Save</button>
            <a href="{% url 'book_list:home' %}" role="button" class="btn btn-outline-secondary mt-4">Cancel</a>
        </div>
        {% if form.non_field_errors %}
            {% for error in form.non_field_errors %}
                <p class="alert alert-danger my-3">{{ error }}</p>
            {% endfor %}
        {% endif %}
    </form>
</div>
{% endblock body %}

{% block js %} {% endblock js %}

book_list/templates/book_list/book_search.html
{% extends 'book_list/base.html' %}

{% block title %} Book Corner - Search Result {% endblock title %}

{% block css %} {% endblock css %}

{% block body %}
{% if books|length < 1 %}
<div class="section mb-4 p-4 text-center">
    <h2 class="text-success">No book found</h2>
    <div>
        <a href="{% url 'book_list:home'%}" class="btn btn-outline-primary mt-4">Back to Home</a>
    </div>
</div>
{% else %}
<div class="section mb-4 px-4 table-responsive">
    <table class="table table-dark table-striped table-hover text-center table-border shadow-sm">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Title</th>
                <th scope="col">Category</th>
                <th scope="col">Author</th>
                <th scope="col">Publication</th>
                <th scope="col">
                    <a href="{% url 'book_list:book-add' %}" class="btn btn-primary btn-sm">
                        <i class="fas fa-plus me-2"></i>Add New Book
                    </a>
                </th>
            </tr>
        </thead>
        <tbody>
            {% for book in books %}
            <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td>{{ book.name }}</td>
                <td>{{ book.category }}</td>
                <td>{{ book.author }}</td>
                <td>{{ book.publication }}</td>
                <td>
                    <a href="{% url 'book_list:book-update' book.id %}" class="btn btn-primary btn-sm me-2">
                        <i class="fas fa-edit"></i></a>
                    <a href="{% url 'book_list:book-delete' book.id %}" class="btn btn-danger btn-sm">
                        <i class="fas fa-trash-alt"></i></a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <div class="mt-4">
        <a href="{% url 'book_list:home'%}" class="btn btn-outline-primary">Back to Home</a>
    </div>
</div>
{% endif %}
{% endblock body %}

{% block js %} {% endblock js %}

book_list/templates/book_list/home.html
{% extends 'book_list/base.html' %}

{% block title %} Book Corner {% endblock title %}

{% block css %} {% endblock css %}

{% block body %}
<div class="section mb-4 p-4">
    <form method="get" action="{% url 'book_list:book-search' %}">
        <div class="input-group">
            <input class="form-control" id="query" name="q" type="search" aria-label="Search"
                   value="{{ request.GET.q }}" placeholder="Search book by title, author, publication or category">
            <button class="btn btn-outline-success" type="submit">
                <i class="fas fa-search me-2"></i>Search
            </button>
        </div>
    </form>
</div>
<div class="section mb-4 px-4 table-responsive">
    <table class="table table-dark table-striped table-hover text-center table-border shadow-sm">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Title</th>
                <th scope="col">Category</th>
                <th scope="col">Author</th>
                <th scope="col">Publication</th>
                <th scope="col">
                    <a href="{% url 'book_list:book-add' %}" class="btn btn-primary btn-sm">
                        <i class="fas fa-plus me-2"></i>Add New Book
                    </a>
                </th>
            </tr>
        </thead>
        <tbody>
            {% for book in books %}
            <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td>{{ book.name }}</td>
                <td>{{ book.category }}</td>
                <td>{{ book.author }}</td>
                <td>{{ book.publication }}</td>
                <td>
                    <a href="{% url 'book_list:book-update' book.id %}" class="btn btn-primary btn-sm me-2">
                        <i class="fas fa-edit"></i></a>
                    <a href="{% url 'book_list:book-delete' book.id %}" class="btn btn-danger btn-sm">
                        <i class="fas fa-trash-alt"></i></a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock body %}

{% block js %} {% endblock js %}